import type { RegisterConfig } from './types'

/** C1 — street light complaints, from a citizen's report to a finished repair. */
export const streetlight: RegisterConfig = {
  key: 'streetlight',
  serviceKey: 'streetlight',
  title: 'সড়কবাতি অভিযোগ ও মেরামত রেজিস্টার',
  section: 'বিদ্যুৎ শাখা',
  serialPrefix: 'SL',
  description: 'নাগরিকের অভিযোগ থেকে মেরামত সম্পন্ন পর্যন্ত প্রতিটি সড়কবাতির হিসাব',
  citizenFacing: true,
  dateField: 'createdAt',
  applicantFields: { name: 'complainant', mobile: 'complainantMobile' },
  createRoles: ['operator', 'electrician'],
  cancelRoles: ['licenceOfficer', 'ceo'],
  steps: [
    { key: 'received', label: 'অভিযোগ গৃহীত', citizenLabel: 'অভিযোগ গৃহীত', actors: [] },
    {
      key: 'assigned',
      label: 'মিস্ত্রি নিযুক্ত',
      citizenLabel: 'মিস্ত্রি পাঠানো হয়েছে',
      actors: ['operator', 'licenceOfficer'],
      requiredFields: ['technician'],
    },
    {
      key: 'repaired',
      label: 'মেরামত সম্পন্ন',
      citizenLabel: 'সমস্যার সমাধান হয়েছে',
      actors: ['electrician'],
      requiredFields: ['repairDate', 'materials'],
    },
  ],
  fields: [
    {
      key: 'poleNo',
      label: 'খুঁটি নং',
      type: 'text',
      showInBook: true,
      citizenInput: true,
      hint: 'জানা না থাকলে ফাঁকা রাখুন',
    },
    { key: 'ward', label: 'ওয়ার্ড', type: 'ward', required: true, showInBook: true, citizenInput: true },
    {
      key: 'road',
      label: 'রাস্তা / এলাকা',
      type: 'text',
      required: true,
      showInBook: true,
      citizenInput: true,
    },
    {
      key: 'faultType',
      label: 'সমস্যার ধরন',
      type: 'select',
      options: ['বাতি নষ্ট', 'তার ছেঁড়া', 'খুঁটি হেলে গেছে', 'সুইচ নষ্ট'],
      required: true,
      showInBook: true,
      citizenInput: true,
    },
    { key: 'photo', label: 'সমস্যার ছবি', type: 'photo', citizenInput: true },
    { key: 'description', label: 'বিবরণ', type: 'textarea', citizenInput: true },
    {
      key: 'complainant',
      label: 'অভিযোগকারীর নাম',
      type: 'text',
      required: true,
      showInBook: true,
      citizenInput: true,
    },
    {
      key: 'complainantMobile',
      label: 'অভিযোগকারীর মোবাইল',
      type: 'phone',
      required: true,
      citizenInput: true,
    },
    { key: 'technician', label: 'নিযুক্ত মিস্ত্রি', type: 'text', showInBook: true, staffOnly: true },
    { key: 'repairDate', label: 'মেরামতের তারিখ', type: 'date', showInBook: true, staffOnly: true },
    { key: 'materials', label: 'ব্যবহৃত মালামাল', type: 'text', showInBook: true, staffOnly: true },
  ],
}
